version: '3'

networks: 
  db-net:

volumes: 
  pg-admin-volume:

services: 
  pg-admin:
    image: dpage/pgadmin4:3.5
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'bruno@me.com'
      PGADMIN_DEFAULT_PASSWORD: 'bruno'
    volumes: 
      - pg-admin-volume:/var/lib/pgadmin
    networks: 
      - db-net
    depends_on: 
      - db 

  db:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - db-net