version: '3'

networks: 
  db-net:

services: 
  pg-admin:
    image: dpage/pgadmin4:3.3
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'bruno@me.com'
      PGADMIN_DEFAULT_PASSWORD: 'bruno'
    networks: 
      - db-net
    depends_on: 
      - db 

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks: 
      - db-net